-- ============================================================
-- 05_ADVANCED_ANALYSIS.SQL
-- E-Commerce Sales & Customer Analytics
-- ============================================================


-- 1. REPEAT CUSTOMERS
-- Customers with more than one completed/non-cancelled order.

SELECT
    customer_id,
    COUNT(order_id) AS total_orders
FROM orders
WHERE order_status <> 'Cancelled'
GROUP BY customer_id
HAVING COUNT(order_id) > 1
ORDER BY total_orders DESC;


-- 2. CUSTOMER LIFETIME VALUE (CLV)
-- Total revenue generated by each customer.

SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    COUNT(o.order_id) AS total_orders,
    ROUND(SUM(o.total_amount), 2) AS lifetime_value
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
WHERE o.order_status <> 'Cancelled'
GROUP BY
    c.customer_id,
    c.first_name,
    c.last_name
ORDER BY lifetime_value DESC;


-- 3. MONTH-OVER-MONTH REVENUE GROWTH
-- Compares current month revenue with previous month.

WITH monthly_sales AS (
    SELECT
        DATE_TRUNC('month', order_date)::DATE AS month,
        ROUND(SUM(total_amount), 2) AS revenue
    FROM orders
    WHERE order_status <> 'Cancelled'
    GROUP BY DATE_TRUNC('month', order_date)
)

SELECT
    month,
    revenue,
    LAG(revenue) OVER (ORDER BY month) AS previous_month,
    ROUND(
        (
            revenue - LAG(revenue) OVER (ORDER BY month)
        ) * 100.0
        / NULLIF(LAG(revenue) OVER (ORDER BY month), 0),
        2
    ) AS growth_percentage
FROM monthly_sales
ORDER BY month;


-- 4. PRODUCT REVENUE RANKING
-- Ranks products from highest to lowest revenue.

WITH product_sales AS (
    SELECT
        p.product_id,
        p.product_name,
        ROUND(
            SUM(
                oi.quantity * oi.unit_price
                * (1 - oi.discount / 100)
            ),
            2
        ) AS revenue
    FROM order_items oi
    JOIN products p
        ON oi.product_id = p.product_id
    JOIN orders o
        ON oi.order_id = o.order_id
    WHERE o.order_status <> 'Cancelled'
    GROUP BY
        p.product_id,
        p.product_name
)

SELECT
    product_id,
    product_name,
    revenue,
    RANK() OVER (ORDER BY revenue DESC) AS revenue_rank
FROM product_sales
ORDER BY revenue_rank;


-- 5. RUNNING REVENUE
-- Calculates cumulative revenue month by month.

WITH monthly_sales AS (
    SELECT
        DATE_TRUNC('month', order_date)::DATE AS month,
        ROUND(SUM(total_amount), 2) AS monthly_revenue
    FROM orders
    WHERE order_status <> 'Cancelled'
    GROUP BY DATE_TRUNC('month', order_date)
)

SELECT
    month,
    monthly_revenue,
    ROUND(
        SUM(monthly_revenue) OVER (
            ORDER BY month
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ),
        2
    ) AS running_revenue
FROM monthly_sales
ORDER BY month;


-- 6. CUSTOMER SEGMENTATION
-- Divides customers into High, Medium and Low value groups.

WITH customer_spending AS (
    SELECT
        customer_id,
        ROUND(SUM(total_amount), 2) AS total_spent
    FROM orders
    WHERE order_status <> 'Cancelled'
    GROUP BY customer_id
)

SELECT
    customer_id,
    total_spent,
    CASE
        WHEN total_spent >= 50000 THEN 'High Value'
        WHEN total_spent >= 20000 THEN 'Medium Value'
        ELSE 'Low Value'
    END AS customer_segment
FROM customer_spending
ORDER BY total_spent DESC;